

mod_id=unbreakables
curse_id=368728
curse_slug=unbreakable-spawner
mod_version=1.0.1
mod_name=unbreakablespawner
mod_group_id=com.lothrazar.unbreakables
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=unbreakable-spawner-og

flib_version=0.2.8
flib_file=8482026
